spring:
  application:
    name: appointment-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${HOSTNAME}}
